" Name:         Solarized 8 Super Light
" Description:  Precision colors for machines and people
" Author:       Ethan Schoonover
" Maintainer:   Lifepillar <lifepillar@lifepillar.me>
" Website:      https://github.com/lifepillar/vim-solarized8
" License:      OSI approved MIT license
" Last Updated: Sun 26 Jan 2020 02:07:30 PM CET

" Generated by Colortemplate v2.0.0

hi clear
if exists('syntax_on')
  syntax reset
endif

let g:colors_name = 'solarized8_super_light'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (((&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')) && !has('iOS')) || has('nvim')

let s:t_Co = get(g:, 'solarized_use16', 0) ? 16 : s:t_Co
let s:italics = s:italics && get(g:, 'solarized_italics', 1)
let s:termtrans = get(g:, 'solarized_termtrans', 0) && !has('gui_running')
hi! link Boolean Constant
hi! link Character Constant
hi! link Conditional Statement
hi! link Debug Special
hi! link Define PreProc
hi! link Delimiter Special
hi! link Exception Statement
hi! link Float Constant
hi! link Function Identifier
hi! link Include PreProc
hi! link Keyword Statement
hi! link Label Statement
hi! link Macro PreProc
hi! link Number Constant
hi! link Operator Statement
hi! link PreCondit PreProc
hi! link QuickFixLine Search
hi! link Repeat Statement
hi! link SpecialChar Special
hi! link SpecialComment Special
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link StorageClass Type
hi! link String Constant
hi! link Structure Type
hi! link Tag Special
hi! link Typedef Type
hi! link lCursor Cursor

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#073642', '#dc322f', '#859900', '#b58900',
        \ '#268bd2', '#d33682', '#2aa198', '#f0f0f0', '#002b36', '#cb4b16',
        \ '#586e75', '#657b83', '#839496', '#6c71c4', '#93a1a1', '#fafafa']
  if has('nvim')
    let g:terminal_color_0 = '#073642'
    let g:terminal_color_1 = '#dc322f'
    let g:terminal_color_2 = '#859900'
    let g:terminal_color_3 = '#b58900'
    let g:terminal_color_4 = '#268bd2'
    let g:terminal_color_5 = '#d33682'
    let g:terminal_color_6 = '#2aa198'
    let g:terminal_color_7 = '#f0f0f0'
    let g:terminal_color_8 = '#002b36'
    let g:terminal_color_9 = '#cb4b16'
    let g:terminal_color_10 = '#586e75'
    let g:terminal_color_11 = '#657b83'
    let g:terminal_color_12 = '#839496'
    let g:terminal_color_13 = '#6c71c4'
    let g:terminal_color_14 = '#93a1a1'
    let g:terminal_color_15 = '#fafafa'
  endif
  if s:termtrans
    hi Normal guifg=#657b83 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi CursorLine guifg=NONE guibg=NONE guisp=#93a1a1 gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
    hi Terminal guifg=fg guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi ToolbarButton guifg=#586e75 guibg=NONE guisp=NONE gui=bold cterm=bold
    hi ToolbarLine guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  else " opaque
    hi Normal guifg=#586e75 guibg=#fafafa guisp=NONE gui=NONE cterm=NONE
    hi CursorLine guifg=NONE guibg=#f0f0f0 guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=fg guibg=#fafafa guisp=NONE gui=NONE cterm=NONE
    hi ToolbarButton guifg=#586e75 guibg=#f0f0f0 guisp=NONE gui=bold cterm=bold
    hi ToolbarLine guifg=NONE guibg=#f0f0f0 guisp=NONE gui=NONE cterm=NONE
  endif
  if get(g:, 'solarized_visibility', '') ==# 'high'
    if get(g:, 'solarized_old_cursor_style', 0)
      hi Cursor guifg=#fafafa guibg=#657b83 guisp=NONE gui=NONE cterm=NONE
    else
      hi Cursor guifg=#fafafa guibg=#dc322f guisp=NONE gui=NONE cterm=NONE
    endif
    hi CursorLineNr guifg=#dc322f guibg=NONE guisp=NONE gui=bold cterm=bold
    hi MatchParen guifg=#cb4b16 guibg=#f0f0f0 guisp=NONE gui=bold,underline cterm=bold,underline
    hi NonText guifg=#dc322f guibg=NONE guisp=NONE gui=bold cterm=bold
    hi SpecialKey guifg=#dc322f guibg=NONE guisp=NONE gui=reverse cterm=reverse
    hi SpellBad guifg=#6c71c4 guibg=#f0f0f0 guisp=#dc322f gui=reverse,undercurl cterm=reverse,undercurl
    hi SpellCap guifg=#6c71c4 guibg=#f0f0f0 guisp=#dc322f gui=reverse,undercurl cterm=reverse,undercurl
    hi SpellLocal guifg=#b58900 guibg=#f0f0f0 guisp=#cb4b16 gui=reverse,undercurl cterm=reverse,undercurl
    hi SpellRare guifg=#2aa198 guibg=#f0f0f0 guisp=#cb4b16 gui=reverse,undercurl cterm=reverse,undercurl
    hi Title guifg=#cb4b16 guibg=NONE guisp=NONE gui=bold cterm=bold
  elseif get(g:, 'solarized_visibility', '') ==# 'low'
    if get(g:, 'solarized_old_cursor_style', 0)
      hi Cursor guifg=#fafafa guibg=#657b83 guisp=NONE gui=NONE cterm=NONE
    else
      hi Cursor guifg=#fafafa guibg=#cb4b16 guisp=NONE gui=NONE cterm=NONE
    endif
    hi CursorLineNr guifg=#93a1a1 guibg=NONE guisp=NONE gui=bold cterm=bold
    hi MatchParen guifg=#cb4b16 guibg=#f0f0f0 guisp=NONE gui=bold cterm=bold
    hi NonText guifg=#f0f0f0 guibg=NONE guisp=NONE gui=bold cterm=bold
    hi SpecialKey guifg=#f0f0f0 guibg=NONE guisp=NONE gui=bold cterm=bold
    hi SpellBad guifg=#6c71c4 guibg=NONE guisp=#6c71c4 gui=undercurl cterm=undercurl
    hi SpellCap guifg=#6c71c4 guibg=NONE guisp=#6c71c4 gui=undercurl cterm=undercurl
    hi SpellLocal guifg=#b58900 guibg=NONE guisp=#b58900 gui=undercurl cterm=undercurl
    hi SpellRare guifg=#2aa198 guibg=NONE guisp=#2aa198 gui=undercurl cterm=undercurl
    hi Title guifg=#93a1a1 guibg=NONE guisp=NONE gui=bold cterm=bold
  else " normal visibility
    if get(g:, 'solarized_old_cursor_style', 0)
      hi Cursor guifg=#fafafa guibg=#657b83 guisp=NONE gui=NONE cterm=NONE
    else
      hi Cursor guifg=#fafafa guibg=#cb4b16 guisp=NONE gui=NONE cterm=NONE
    endif
    hi CursorLineNr guifg=#657b83 guibg=NONE guisp=NONE gui=bold cterm=bold
    hi MatchParen guifg=#002b36 guibg=#f0f0f0 guisp=NONE gui=bold cterm=bold
    hi NonText guifg=#839496 guibg=NONE guisp=NONE gui=bold cterm=bold
    hi SpecialKey guifg=#839496 guibg=#f0f0f0 guisp=NONE gui=bold cterm=bold
    hi SpellBad guifg=#6c71c4 guibg=NONE guisp=#6c71c4 gui=undercurl cterm=undercurl
    hi SpellCap guifg=#6c71c4 guibg=NONE guisp=#6c71c4 gui=undercurl cterm=undercurl
    hi SpellLocal guifg=#b58900 guibg=NONE guisp=#b58900 gui=undercurl cterm=undercurl
    hi SpellRare guifg=#2aa198 guibg=NONE guisp=#2aa198 gui=undercurl cterm=undercurl
    hi Title guifg=#cb4b16 guibg=NONE guisp=NONE gui=bold cterm=bold
  endif
  if get(g:, 'solarized_diffmode', '') ==# 'high'
    hi DiffAdd guifg=#859900 guibg=NONE guisp=NONE gui=reverse cterm=reverse
    hi DiffChange guifg=#b58900 guibg=NONE guisp=NONE gui=reverse cterm=reverse
    hi DiffDelete guifg=#dc322f guibg=NONE guisp=NONE gui=reverse cterm=reverse
    hi DiffText guifg=#268bd2 guibg=NONE guisp=NONE gui=reverse cterm=reverse
  elseif get(g:, 'solarized_diffmode', '') ==# 'low'
    hi DiffAdd guifg=#859900 guibg=NONE guisp=#859900 gui=NONE cterm=NONE
    hi DiffChange guifg=#b58900 guibg=NONE guisp=#b58900 gui=NONE cterm=NONE
    hi DiffDelete guifg=#dc322f guibg=NONE guisp=NONE gui=bold cterm=bold
    hi DiffText guifg=#268bd2 guibg=NONE guisp=#268bd2 gui=NONE cterm=NONE
  else " normal diffmode
    hi DiffAdd guifg=#859900 guibg=#f0f0f0 guisp=#859900 gui=NONE cterm=NONE
    hi DiffChange guifg=#b58900 guibg=#f0f0f0 guisp=#b58900 gui=NONE cterm=NONE
    hi DiffDelete guifg=#dc322f guibg=#f0f0f0 guisp=NONE gui=bold cterm=bold
    hi DiffText guifg=#268bd2 guibg=#f0f0f0 guisp=#268bd2 gui=NONE cterm=NONE
  endif
  if get(g:, 'solarized_statusline', '') ==# 'low'
    hi StatusLine guifg=#f0f0f0 guibg=#586e75 guisp=NONE gui=bold,reverse cterm=bold,reverse
    hi StatusLineNC guifg=#f0f0f0 guibg=#93a1a1 guisp=NONE gui=reverse cterm=reverse
    hi TabLineSel guifg=#586e75 guibg=#f0f0f0 guisp=NONE gui=NONE cterm=NONE
    hi NormalMode guifg=#f0f0f0 guibg=#586e75 guisp=NONE gui=bold,reverse cterm=bold,reverse
  else
    hi StatusLine guifg=#f0f0f0 guibg=#073642 guisp=NONE gui=reverse cterm=reverse
    hi StatusLineNC guifg=#f0f0f0 guibg=#586e75 guisp=NONE gui=reverse cterm=reverse
    hi TabLineSel guifg=#073642 guibg=#f0f0f0 guisp=NONE gui=NONE cterm=NONE
    hi NormalMode guifg=#f0f0f0 guibg=#073642 guisp=NONE gui=reverse cterm=reverse
  endif
  hi ColorColumn guifg=NONE guibg=#f0f0f0 guisp=NONE gui=NONE cterm=NONE
  hi Conceal guifg=#268bd2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi CursorColumn guifg=NONE guibg=#f0f0f0 guisp=NONE gui=NONE cterm=NONE
  hi Directory guifg=#268bd2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi EndOfBuffer guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi ErrorMsg guifg=#dc322f guibg=#fafafa guisp=NONE gui=reverse cterm=reverse
  hi FoldColumn guifg=#657b83 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Folded guifg=#657b83 guibg=NONE guisp=#fafafa gui=bold cterm=bold
  hi IncSearch guifg=#cb4b16 guibg=NONE guisp=NONE gui=standout cterm=standout
  hi LineNr guifg=#93a1a1 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ModeMsg guifg=#268bd2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi MoreMsg guifg=#268bd2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#657b83 guibg=#f0f0f0 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSbar guifg=NONE guibg=#f0f0f0 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSel guifg=#fafafa guibg=#93a1a1 guisp=NONE gui=NONE cterm=NONE
  hi PmenuThumb guifg=NONE guibg=#93a1a1 guisp=NONE gui=NONE cterm=NONE
  hi Question guifg=#2aa198 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Search guifg=#b58900 guibg=NONE guisp=NONE gui=reverse cterm=reverse
  hi SignColumn guifg=#657b83 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi TabLine guifg=#93a1a1 guibg=#f0f0f0 guisp=NONE gui=NONE cterm=NONE
  hi TabLineFill guifg=#93a1a1 guibg=#f0f0f0 guisp=NONE gui=NONE cterm=NONE
  hi VertSplit guifg=#93a1a1 guibg=#f0f0f0 guisp=NONE gui=NONE cterm=NONE
  hi Visual guifg=#93a1a1 guibg=#fafafa guisp=NONE gui=reverse cterm=reverse
  hi VisualNOS guifg=NONE guibg=#f0f0f0 guisp=NONE gui=reverse cterm=reverse
  hi WarningMsg guifg=#cb4b16 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi WildMenu guifg=#93a1a1 guibg=#fafafa guisp=NONE gui=reverse cterm=reverse
  hi Comment guifg=#93a1a1 guibg=NONE guisp=NONE gui=italic cterm=italic
  hi Constant guifg=#2aa198 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi CursorIM guifg=NONE guibg=fg guisp=NONE gui=NONE cterm=NONE
  hi Error guifg=#dc322f guibg=#fafafa guisp=NONE gui=bold,reverse cterm=bold,reverse
  hi Identifier guifg=#268bd2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Ignore guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi PreProc guifg=#cb4b16 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Special guifg=#cb4b16 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Statement guifg=#859900 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Todo guifg=#d33682 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Type guifg=#b58900 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Underlined guifg=#6c71c4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi InsertMode guifg=#f0f0f0 guibg=#2aa198 guisp=NONE gui=bold,reverse cterm=bold,reverse
  hi ReplaceMode guifg=#f0f0f0 guibg=#cb4b16 guisp=NONE gui=bold,reverse cterm=bold,reverse
  hi VisualMode guifg=#f0f0f0 guibg=#d33682 guisp=NONE gui=bold,reverse cterm=bold,reverse
  hi CommandMode guifg=#f0f0f0 guibg=#d33682 guisp=NONE gui=bold,reverse cterm=bold,reverse
  if !s:italics
    hi Comment gui=NONE cterm=NONE
  endif
  if has('nvim')
    hi! link TermCursor Cursor
    hi TermCursorNC guifg=#fafafa guibg=#93a1a1 guisp=NONE gui=NONE cterm=NONE
  endif
  if !get(g:, 'solarized_extra_hi_groups', 0)
    unlet s:t_Co s:italics s:termtrans
    finish
  endif
  hi! link vimVar Identifier
  hi! link vimFunc Function
  hi! link vimUserFunc Function
  hi! link helpSpecial Special
  hi! link vimSet Normal
  hi! link vimSetEqual Normal
  hi vimCommentString guifg=#6c71c4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi vimCommand guifg=#b58900 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi vimCmdSep guifg=#268bd2 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi helpExample guifg=#586e75 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi helpOption guifg=#2aa198 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi helpNote guifg=#d33682 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi helpVim guifg=#d33682 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi helpHyperTextJump guifg=#268bd2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi helpHyperTextEntry guifg=#859900 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi vimIsCommand guifg=#839496 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi vimSynMtchOpt guifg=#b58900 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi vimSynType guifg=#2aa198 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi vimHiLink guifg=#268bd2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi vimHiGroup guifg=#268bd2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi vimGroup guifg=#268bd2 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi! link diffAdded Statement
  hi! link diffLine Identifier
  hi gitcommitComment guifg=#93a1a1 guibg=NONE guisp=NONE gui=italic cterm=italic
  hi! link gitcommitUntracked gitcommitComment
  hi! link gitcommitDiscarded gitcommitComment
  hi! link gitcommitSelected gitcommitComment
  hi gitcommitUnmerged guifg=#859900 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi gitcommitOnBranch guifg=#93a1a1 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi gitcommitBranch guifg=#d33682 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi! link gitcommitNoBranch gitcommitBranch
  hi gitcommitdiscardedtype guifg=#dc322f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi gitcommitselectedtype guifg=#859900 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi gitcommitHeader guifg=#93a1a1 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi gitcommitUntrackedFile guifg=#2aa198 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi gitcommitDiscardedFile guifg=#dc322f guibg=NONE guisp=NONE gui=bold cterm=bold
  hi gitcommitSelectedFile guifg=#859900 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi gitcommitUnmergedFile guifg=#b58900 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi gitcommitFile guifg=#657b83 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi! link gitcommitDiscardedArrow gitcommitDiscardedFile
  hi! link gitcommitSelectedArrow gitcommitSelectedFile
  hi! link gitcommitUnmergedArrow gitcommitUnmergedFile
  hi htmlTag guifg=#93a1a1 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi htmlEndTag guifg=#93a1a1 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi htmlTagN guifg=#586e75 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi htmlTagName guifg=#268bd2 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi htmlSpecialTagName guifg=#268bd2 guibg=NONE guisp=NONE gui=italic cterm=italic
  hi htmlArg guifg=#839496 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi javaScript guifg=#b58900 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link jsFuncCall Function
  hi perlHereDoc guifg=#586e75 guibg=#fafafa guisp=NONE gui=NONE cterm=NONE
  hi perlVarPlain guifg=#b58900 guibg=#fafafa guisp=NONE gui=NONE cterm=NONE
  hi perlStatementFileDesc guifg=#2aa198 guibg=#fafafa guisp=NONE gui=NONE cterm=NONE
  hi texstatement guifg=#2aa198 guibg=#fafafa guisp=NONE gui=NONE cterm=NONE
  hi texmathzonex guifg=#b58900 guibg=#fafafa guisp=NONE gui=NONE cterm=NONE
  hi texmathmatcher guifg=#b58900 guibg=#fafafa guisp=NONE gui=NONE cterm=NONE
  hi texreflabel guifg=#b58900 guibg=#fafafa guisp=NONE gui=NONE cterm=NONE
  hi rubyDefine guifg=#586e75 guibg=#fafafa guisp=NONE gui=bold cterm=bold
  hi! link rubySymbol Type
  hi rubyBoolean guifg=#d33682 guibg=#fafafa guisp=NONE gui=NONE cterm=NONE
  hi cPreCondit guifg=#cb4b16 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi VarId guifg=#268bd2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ConId guifg=#b58900 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi hsImport guifg=#d33682 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi hsString guifg=#839496 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi hsStructure guifg=#2aa198 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi hs_hlFunctionName guifg=#268bd2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi hsStatement guifg=#2aa198 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi hsImportLabel guifg=#2aa198 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi hs_OpFunctionName guifg=#b58900 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi hs_DeclareFunction guifg=#cb4b16 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi hsVarSym guifg=#2aa198 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi hsType guifg=#b58900 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi hsTypedef guifg=#2aa198 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi hsModuleName guifg=#859900 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link hsImportParams Delimiter
  hi! link hsDelimTypeExport Delimiter
  hi! link hsModuleStartLabel hsStructure
  hi! link hsModuleWhereLabel hsModuleStartLabel
  hi hsNiceOperator guifg=#2aa198 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi hsniceoperator guifg=#2aa198 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  if !s:italics
    hi gitcommitComment gui=NONE cterm=NONE
    hi htmlSpecialTagName gui=NONE cterm=NONE
  endif
  let hs_highlight_boolean=1
  let hs_highlight_delimiters=1
  hi pandocTitleBlock guifg=#268bd2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pandocTitleBlockTitle guifg=#268bd2 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi pandocTitleComment guifg=#268bd2 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi pandocComment guifg=#93a1a1 guibg=NONE guisp=NONE gui=italic cterm=italic
  hi pandocVerbatimBlock guifg=#b58900 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link pandocVerbatimBlockDeep pandocVerbatimBlock
  hi! link pandocCodeBlock pandocVerbatimBlock
  hi! link pandocCodeBlockDelim pandocVerbatimBlock
  hi pandocBlockQuote guifg=#268bd2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pandocBlockQuoteLeader1 guifg=#268bd2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pandocBlockQuoteLeader2 guifg=#2aa198 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pandocBlockQuoteLeader3 guifg=#b58900 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pandocBlockQuoteLeader4 guifg=#dc322f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pandocBlockQuoteLeader5 guifg=#657b83 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pandocBlockQuoteLeader6 guifg=#93a1a1 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pandocListMarker guifg=#d33682 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pandocListReference guifg=#d33682 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pandocDefinitionBlock guifg=#6c71c4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pandocDefinitionTerm guifg=#6c71c4 guibg=NONE guisp=NONE gui=standout cterm=standout
  hi pandocDefinitionIndctr guifg=#6c71c4 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi pandocEmphasisDefinition guifg=#6c71c4 guibg=NONE guisp=NONE gui=italic cterm=italic
  hi pandocEmphasisNestedDefinition guifg=#6c71c4 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi pandocStrongEmphasisDefinition guifg=#6c71c4 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi pandocStrongEmphasisNestedDefinition guifg=#6c71c4 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi pandocStrongEmphasisEmphasisDefinition guifg=#6c71c4 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi pandocStrikeoutDefinition guifg=#6c71c4 guibg=NONE guisp=NONE gui=reverse cterm=reverse
  hi pandocVerbatimInlineDefinition guifg=#6c71c4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pandocSuperscriptDefinition guifg=#6c71c4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pandocSubscriptDefinition guifg=#6c71c4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pandocTable guifg=#268bd2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pandocTableStructure guifg=#268bd2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link pandocTableStructureTop pandocTableStructre
  hi! link pandocTableStructureEnd pandocTableStructre
  hi pandocTableZebraLight guifg=#268bd2 guibg=#fafafa guisp=NONE gui=NONE cterm=NONE
  hi pandocTableZebraDark guifg=#268bd2 guibg=#f0f0f0 guisp=NONE gui=NONE cterm=NONE
  hi pandocEmphasisTable guifg=#268bd2 guibg=NONE guisp=NONE gui=italic cterm=italic
  hi pandocEmphasisNestedTable guifg=#268bd2 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi pandocStrongEmphasisTable guifg=#268bd2 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi pandocStrongEmphasisNestedTable guifg=#268bd2 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi pandocStrongEmphasisEmphasisTable guifg=#268bd2 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi pandocStrikeoutTable guifg=#268bd2 guibg=NONE guisp=NONE gui=reverse cterm=reverse
  hi pandocVerbatimInlineTable guifg=#268bd2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pandocSuperscriptTable guifg=#268bd2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pandocSubscriptTable guifg=#268bd2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pandocHeading guifg=#cb4b16 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi pandocHeadingMarker guifg=#cb4b16 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi pandocEmphasisHeading guifg=#cb4b16 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi pandocEmphasisNestedHeading guifg=#cb4b16 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi pandocStrongEmphasisHeading guifg=#cb4b16 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi pandocStrongEmphasisNestedHeading guifg=#cb4b16 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi pandocStrongEmphasisEmphasisHeading guifg=#cb4b16 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi pandocStrikeoutHeading guifg=#cb4b16 guibg=NONE guisp=NONE gui=reverse cterm=reverse
  hi pandocVerbatimInlineHeading guifg=#cb4b16 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi pandocSuperscriptHeading guifg=#cb4b16 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi pandocSubscriptHeading guifg=#cb4b16 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi pandocLinkDelim guifg=#93a1a1 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pandocLinkLabel guifg=#268bd2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pandocLinkText guifg=#268bd2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pandocLinkURL guifg=#839496 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pandocLinkTitle guifg=#839496 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pandocLinkTitleDelim guifg=#93a1a1 guibg=NONE guisp=#839496 gui=NONE cterm=NONE
  hi pandocLinkDefinition guifg=#2aa198 guibg=NONE guisp=#839496 gui=NONE cterm=NONE
  hi pandocLinkDefinitionID guifg=#268bd2 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi pandocImageCaption guifg=#6c71c4 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi pandocFootnoteLink guifg=#859900 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pandocFootnoteDefLink guifg=#859900 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi pandocFootnoteInline guifg=#859900 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi pandocFootnote guifg=#859900 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pandocCitationDelim guifg=#d33682 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pandocCitation guifg=#d33682 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pandocCitationID guifg=#d33682 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pandocCitationRef guifg=#d33682 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pandocStyleDelim guifg=#93a1a1 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pandocEmphasis guifg=#657b83 guibg=NONE guisp=NONE gui=italic cterm=italic
  hi pandocEmphasisNested guifg=#657b83 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi pandocStrongEmphasis guifg=#657b83 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi pandocStrongEmphasisNested guifg=#657b83 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi pandocStrongEmphasisEmphasis guifg=#657b83 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi pandocStrikeout guifg=#93a1a1 guibg=NONE guisp=NONE gui=reverse cterm=reverse
  hi pandocVerbatimInline guifg=#b58900 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pandocSuperscript guifg=#6c71c4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pandocSubscript guifg=#6c71c4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pandocRule guifg=#268bd2 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi pandocRuleLine guifg=#268bd2 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi pandocEscapePair guifg=#dc322f guibg=NONE guisp=NONE gui=bold cterm=bold
  hi pandocCitationRef guifg=#d33682 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pandocNonBreakingSpace guifg=#dc322f guibg=NONE guisp=NONE gui=reverse cterm=reverse
  hi! link pandocEscapedCharacter pandocEscapePair
  hi! link pandocLineBreak pandocEscapePair
  hi pandocMetadataDelim guifg=#93a1a1 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pandocMetadata guifg=#268bd2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pandocMetadataKey guifg=#268bd2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pandocMetadata guifg=#268bd2 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi! link pandocMetadataTitle pandocMetadata
  if !s:italics
    hi pandocComment gui=NONE cterm=NONE
    hi pandocEmphasisDefinition gui=NONE cterm=NONE
    hi pandocEmphasisTable gui=NONE cterm=NONE
    hi pandocEmphasis gui=NONE cterm=NONE
  endif
  if get(g:, 'solarized_statusline', '') ==# 'flat'
    hi ALEErrorSign guifg=#dc322f guibg=NONE guisp=NONE gui=bold cterm=bold
    hi ALEInfoSign guifg=#2aa198 guibg=NONE guisp=NONE gui=bold cterm=bold
    hi ALEWarningSign guifg=#b58900 guibg=NONE guisp=NONE gui=bold cterm=bold
    hi ALEErrorSignLineNr guifg=#dc322f guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi ALEInfoSignLineNr guifg=#2aa198 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi ALEWarningSignLineNr guifg=#b58900 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  else
    if get(g:, 'ale_sign_highlight_linenrs', '') ==# 1
      hi ALEErrorSign guifg=#f0f0f0 guibg=#dc322f guisp=NONE gui=bold cterm=bold
      hi ALEInfoSign guifg=#f0f0f0 guibg=#2aa198 guisp=NONE gui=bold cterm=bold
      hi ALEWarningSign guifg=#f0f0f0 guibg=#b58900 guisp=NONE gui=bold cterm=bold
    else
      hi ALEErrorSign guifg=#dc322f guibg=#f0f0f0 guisp=NONE gui=bold cterm=bold
      hi ALEInfoSign guifg=#2aa198 guibg=#f0f0f0 guisp=NONE gui=bold cterm=bold
      hi ALEWarningSign guifg=#b58900 guibg=#f0f0f0 guisp=NONE gui=bold cterm=bold
    endif
    hi ALEErrorSignLineNr guifg=#f0f0f0 guibg=#dc322f guisp=NONE gui=NONE cterm=NONE
    hi ALEInfoSignLineNr guifg=#f0f0f0 guibg=#2aa198 guisp=NONE gui=NONE cterm=NONE
    hi ALEWarningSignLineNr guifg=#f0f0f0 guibg=#b58900 guisp=NONE gui=NONE cterm=NONE
  endif
  hi ALEError guifg=#dc322f guibg=NONE guisp=#dc322f gui=undercurl cterm=undercurl
  hi ALEErrorLine guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi ALEInfo guifg=#2aa198 guibg=NONE guisp=#2aa198 gui=undercurl cterm=undercurl
  hi ALEInfoLine guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi ALEWarning guifg=#b58900 guibg=NONE guisp=#b58900 gui=undercurl cterm=undercurl
  hi ALEWarningLine guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi! link ALEStyleError ALEError
  hi! link ALEStyleErrorSign ALEErrorSign
  hi! link ALEStyleErrorSignLineNr ALEErrorSignLineNr
  hi! link ALEStyleWarning ALEWarning
  hi! link ALEStyleWarningSign ALEWarningSign
  hi! link ALEStyleWarningSignLineNr ALEWarningSignLineNr
  unlet s:termtrans
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 2
  hi Normal term=NONE
  hi ColorColumn term=reverse
  hi Conceal term=NONE
  hi Cursor term=NONE
  hi CursorColumn term=reverse
  hi CursorLine term=underline
  hi CursorLineNr term=bold,italic,reverse,underline
  hi DiffAdd term=reverse,underline
  hi DiffChange term=reverse,underline
  hi DiffDelete term=reverse,underline
  hi DiffText term=bold,reverse,underline
  hi Directory term=NONE
  hi EndOfBuffer term=NONE
  hi ErrorMsg term=bold,italic,reverse
  hi FoldColumn term=reverse
  hi Folded term=italic,reverse,underline
  hi IncSearch term=bold,italic,reverse
  hi LineNr term=reverse
  hi MatchParen term=bold,underline
  hi ModeMsg term=NONE
  hi MoreMsg term=NONE
  hi NonText term=NONE
  hi Pmenu term=reverse
  hi PmenuSbar term=NONE
  hi PmenuSel term=NONE
  hi PmenuThumb term=NONE
  hi Question term=standout
  hi Search term=italic,underline
  hi SignColumn term=reverse
  hi SpecialKey term=bold
  hi SpellBad term=italic,underline
  hi SpellCap term=italic,underline
  hi SpellLocal term=italic,underline
  hi SpellRare term=italic,underline
  hi StatusLine term=bold,reverse
  hi StatusLineNC term=reverse
  hi TabLine term=italic,reverse,underline
  hi TabLineFill term=reverse,underline
  hi TabLineSel term=bold
  hi Title term=bold
  hi VertSplit term=reverse
  hi Visual term=reverse
  hi VisualNOS term=NONE
  hi WarningMsg term=standout
  hi WildMenu term=bold
  hi Comment term=italic
  hi Constant term=bold,italic
  hi Error term=reverse
  hi Identifier term=italic
  hi Ignore term=NONE
  hi PreProc term=italic
  hi Special term=bold,italic
  hi Statement term=bold
  hi Todo term=bold,underline
  hi Type term=bold
  hi Underlined term=underline
  hi CursorIM term=NONE
  hi ToolbarLine term=reverse
  hi ToolbarButton term=bold,reverse
  if !s:italics
    hi CursorLineNr term=bold,reverse,underline
    hi ErrorMsg term=bold,reverse
    hi Folded term=reverse,underline
    hi IncSearch term=bold,reverse
    hi Search term=underline
    hi SpellBad term=underline
    hi SpellCap term=underline
    hi SpellLocal term=underline
    hi SpellRare term=underline
    hi TabLine term=reverse,underline
    hi Comment term=NONE
    hi Constant term=bold
    hi Identifier term=NONE
    hi PreProc term=NONE
    hi Special term=bold
  endif
  unlet s:termtrans
  unlet s:t_Co s:italics
  finish
endif

" Background: any
" Color: base2    #073642   236    0
" Color: red      #dc322f   160    1
" Color: green    #859900   106    2
" Color: yellow   #b58900   136    3
" Color: blue     #268bd2   32     4
" Color: magenta  #d33682   162    5
" Color: cyan     #2aa198   37     6
" Color: base02   #f0f0f0   254    7
" Color: base3    #002b36   235    8
" Color: orange   #cb4b16   166    9
" Color: base1    #586e75   242   10
" Color: base0    #657b83   66    11
" Color: base00   #839496   246   12
" Color: violet   #6c71c4   61    13
" Color: base01   #93a1a1   247   14
" Color: base03   #fafafa   230   15
" Color: back     #fafafa   230   15
" Term Colors: base2  red    green  yellow blue   magenta cyan   base02
" Term Colors: base3  orange base1  base0  base00 violet  base01 base03
" Background: any
" vim: et ts=2 sw=2
